name: configuration-data
language: python
variables:
  - name: output
    inputType: OutputTopic
    multiline: false
    description: Name of the output topic to write into
    defaultValue: configuration
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
