name: mongodb-sink-2
language: python
variables:
  - name: input
    inputType: InputTopic
    description: The input Kafka topic name
    defaultValue: danger_condition
    required: true
  - name: MONGODB_HOST
    inputType: FreeText
    description: MongoDB host name
    defaultValue: mongodb
    required: true
  - name: MONGODB_USERNAME
    inputType: FreeText
    description: MongoDB username
    defaultValue: admin
    required: true
  - name: MONGODB_PASSWORD
    inputType: Secret
    description: MongoDB password
    defaultValue: mongo_root_password
    required: true
  - name: MONGODB_DB
    inputType: FreeText
    description: MongoDB database name
    defaultValue: solar_db
    required: true
  - name: MONGODB_COLLECTION
    inputType: FreeText
    description: MongoDB collection name
    defaultValue: error_conditions
    required: true
  - name: MONGODB_PORT
    inputType: FreeText
    description: MongoDB host port
    defaultValue: 27017
  - name: MONGODB_DOCUMENT_MATCHER
    inputType: FreeText
    description: How documents are selected to update; accepts a JSON-serializable string formatted as a MongoDB filter Query.
  - name: MONGODB_UPSERT
    inputType: FreeText
    description: Boolean to create documents if no matches with MONGODB_DOCUMENT_MATCHER
    defaultValue: true
  - name: MONGODB_UPDATE_METHOD
    inputType: FreeText
    description: How documents found with MONGODB_DOCUMENT_MATCHER are updated
    defaultValue: UpdateOne
  - name: MONGODB_ADD_MESSAGE_METADATA
    inputType: FreeText
    description: Boolean to include key, timestamp, and headers as '__{field}'
    defaultValue: false
  - name: MONGODB_ADD_TOPIC_METADATA
    inputType: FreeText
    description: Boolean to include topic, partition, and offset as '__{field}'
    defaultValue: false
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    description: The name of the consumer group to use when consuming from Kafka
    defaultValue: quixstreams-mongodb-sink
    required: true
  - name: BUFFER_SIZE
    inputType: FreeText
    description: The number of records that sink waits before flushing data to MongoDB
    defaultValue: 1000
  - name: BUFFER_TIMEOUT
    inputType: FreeText
    description: The number of seconds that sink waits before flushing data to MongoDB
    defaultValue: 1
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: mongodb-destination
